service: e-commerce-apis

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  stage: dev
  memorySize: 2048
  timeout: 15
  lambdaHashingVersion: 20201221


functions:
  hello:
    handler: handler.hello
    events: 
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: 5000
      MONGODB_URI: mongodb+srv://tbuda:qwer1234@cluster0.zplvv3g.mongodb.net/ecommerce_db?retryWrites=true&w=majority
      JWT_SECRET: mysecret
